[[types]]
glob = "examples/universe.ron"
type = "crate::data::UniverseDefinition"

[[types]]
glob = "examples/example_universe/materials"
type = "crate::data::MaterialDefinition"

[[types]]
glob = "examples/example_universe/textures"
type = "crate::data::TextureDefinition"

[[types]]
glob = "examples/example_universe/blocks"
type = "crate::data::BlockDefinition"

